name: Update RSS Reader

on:
  push:
  workflow_dispatch:

jobs:
  update:
    name: 'Update RSS Reader'
    runs-on: ubuntu-latest
    steps:
      - uses: eddmann/github-rss-reader@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          template: |
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>My GitHub RSS Reader</title>
              <link rel="stylesheet" href="https://unpkg.com/axist@latest/dist/axist.min.css" />
              <style>
                h3 { margin-top: 150px; }
                h5 { margin-top: 100px; }
              </style>
            </head>
            <body>
              {% set current_date = "" %}
              {% for post in posts | sort(attribute="date") | reverse | slice(end=25) %}
                {% set new_date = post.date | date(format="%e %B") %}
                {% if current_date != new_date %}
                  {% set_global current_date = new_date %}
                  <h3>{{ new_date }}</h3>
                {% endif %}
                <h5>{{ post.title }}</h5>
                <p>📝 <a href="{{ post.feed_url }}">{{ post.feed_title }}</a></p>
                <blockquote>{{ post.description | striptags | trim | truncate(length=250) }}</blockquote>
                <a href='{{ post.url }}' target='_blank'>Read more…</a>
              {% endfor %}
            </body>
            </html>
          feeds: |
            https://feeds.feedburner.com/symfony/blog
            https://blog.jetbrains.com/phpstorm/feed/
            https://eddmann.com/rss.xml
