name: Update RSS Reader

on:
  push:
  workflow_dispatch:

jobs:
  update:
    name: 'Update RSS Reader'
    runs-on: ubuntu-latest
    steps:
      - uses: eddmann/github-rss-reader@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          template: |
            <!DOCTYPE html>
            <html lang='en'>
            <head>
            <meta charset='UTF-8' />
            <meta name='viewport' content='width=device-width, initial-scale=1.0' />
            <title>GitHub RSS Reader</title>
            <link rel='stylesheet' href='//fonts.xz.style/serve/inter.css' />
            <link rel='stylesheet' href='//cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css' />
            </head>
            <body>
            <header>
            <h1>GitHub RSS Reader</h1>
            </header>
            {% set current_date = "" %}
            {% for post in posts | sort(attribute="date") | reverse | slice(end=25) %}
              {% if current_date != post.date | date %}
                {% set current_date = post.date | date %}
                <h2>{{ current_date }}</h2>
              {% endif %}
              <h4>{{ post.title }}</h4>
              <a href="{{ post.feed_url }}">{{ post.feed_title }}</a>
              <time datetime='{{ post.date }}'>{{ post.date }}</date>
              <p>{{ post.description | striptags | trim | truncate(length=250) }}</p>
              <a href='{{ post.url }}' target='_blank'>Read more</a>
            {% endfor %}
            </body>
            </html>
          feeds: |
            https://feeds.feedburner.com/symfony/blog
            https://blog.jetbrains.com/phpstorm/feed/
            https://eddmann.com/rss.xml
