name: Update RSS Reader

on:
  push:
  workflow_dispatch:

jobs:
  update:
    name: 'Update RSS Reader'
    runs-on: ubuntu-latest
    steps:
      - uses: eddmann/github-rss-reader@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          template: |
            <!DOCTYPE html>
            <html lang='en'>
            <head>
            <meta charset='UTF-8' />
            <meta name='viewport' content='width=device-width, initial-scale=1.0' />
            <title>GitHub RSS Reader</title>
            <link rel='stylesheet' href='//fonts.xz.style/serve/inter.css' />
            <link rel='stylesheet' href='//cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css' />
            </head>
            <body>
            <header>
            <h1>GitHub RSS Reader</h1>
            </header>
            {% for post in posts %}
            <h4>{{ post.title }}</h4>
            {{ post.date | date(format="%d-%m-%Y") }}
            <a href="{{ post.feed_url }}">{{ post.feed_title }}</a><br />
            <time datetime='{{ post.date }}'>{{ post.date }}</date>
            <pre>{{ post.description | striptags | trim | truncate(length=250) }}</pre>
            <a href='{{ post.url }}' target='_blank'>Read more</a>
            {% endfor %}
            </body>
            </html>
          feeds: |
            https://feeds.feedburner.com/symfony/blog
            https://blog.jetbrains.com/phpstorm/feed/
            https://eddmann.com/rss.xml
